#!/usr/bin/env python

import sys
from PyQt4 import QtGui
from episoderenamer_gui import EpisodeRenamerGUI

if __name__ == "__main__":
	app = QtGui.QApplication(sys.argv)
	ergui = EpisodeRenamerGUI()
	ergui.show()
	sys.exit(app.exec_())
